# Generated by Django 5.2.9 on 2025-12-28 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='recommended_products',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
